// redefine them ... structure them ... 
// gps and timer varables
unsigned char time[6], date[6], lat[10], lon[11];
// flash and xbee buffer ... 
unsigned char data[528];
// other buffers ... 
// note : don't define the buffers for usart etc ., here ... coz : that need to be FIFO buffers ... take help from RTOS.
